/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 head.glb 
Author: DEDROX (https://sketchfab.com/Raghavprasanna)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cyberpunk-vr-head-rig-dbaf4b552a814f1ea7b27e4488a0c9f2
Title: Cyberpunk VR head rig
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Head(props) {
  const { nodes, materials } = useGLTF("/models/head-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Object_10.geometry}
          material={materials.Paint_Gloss_White}
        />
        <mesh
          geometry={nodes.Object_11.geometry}
          material={materials.Paint_Gloss_White}
        />
        <mesh
          geometry={nodes.Object_12.geometry}
          material={materials.Paint_Gloss_White}
        />
      </group>
      <mesh
        geometry={nodes.Object_4.geometry}
        material={materials["Material.001"]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_6.geometry}
        material={materials.Material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_8.geometry}
        material={materials["Material.005"]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_14.geometry}
        material={materials["Material.002"]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_16.geometry}
        material={materials["Material.003"]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_18.geometry}
        material={materials["Material.004"]}
      />
    </group>
  );
}

useGLTF.preload("/models/head-transformed.glb");
