/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 headOpt.glb -T 
Files: headOpt.glb [8.83MB] > E:\full-stack\portfolio\public\models\headOpt-transformed.glb [659.22KB] (93%)
Author: DEDROX (https://sketchfab.com/Raghavprasanna)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cyberpunk-vr-head-rig-dbaf4b552a814f1ea7b27e4488a0c9f2
Title: Cyberpunk VR head rig
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function HeadOpt(props) {
  const { nodes, materials } = useGLTF("/models/headOpt-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Object_4.geometry}
        material={materials.PaletteMaterial001}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_10.geometry}
        material={materials.PaletteMaterial002}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_16.geometry}
        material={materials.PaletteMaterial003}
        rotation={[Math.PI / 2, 0, 0]}
      />
      {/* <mesh
        geometry={nodes.Object_18.geometry}
        material={materials.PaletteMaterial004}
      /> */}
    </group>
  );
}

useGLTF.preload("/models/headOpt-transformed.glb");
