/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 pc.glb 
Author: Lee Alex Johansson (https://sketchfab.com/lee.johansson)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/weathered-workstation-dc877404be0445f0a855e37f2747794a
Title: Weathered Workstation
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Pc(props) {
  const { nodes, materials } = useGLTF("/models/pc.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.desk} />
        <mesh
          geometry={nodes.Object_3.geometry}
          material={materials.wire_224198087}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/pc.glb");
