/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 shape.glb --transform 
Files: shape.glb [6.02MB] > E:\full-stack\portfolio\public\models\shape-transformed.glb [509.76KB] (92%)
Author: smice (https://sketchfab.com/smice)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/fantasy-ball-978aef525c794b81ac56f58c8e4802cf
Title: Fantasy Ball
*/

import React from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function Shape(props) {
  const group = React.useRef();
  const { nodes, materials, animations } = useGLTF(
    "/models/shape-transformed.glb"
  );
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="GLTF_SceneRootNode">
          <group name="1_4">
            <mesh
              name="Object_4"
              geometry={nodes.Object_4.geometry}
              material={materials.Iridescent}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/shape-transformed.glb");
